name: Portable build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    name: Portable code on macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the portable code
        run: cmake --build build --target pulsar_portable --parallel
